### ISSUE TITLE
Parallax Feature Image with Overlay

### ISSUE THREAD

**Issue by mgl97t** [shoutem/animation#10]
I am trying to create a view with the image on top that scales when pulled and parallaxes when scrolled up. You have one on your video on http://shoutem.github.io it is one the with Game of Thrones. I am guessing that it is done with your animations. Could your help me understand how to build this? Maybe some example code? This always helps me be able to tear it apart and learn what is going on.

I was not abe to get your examples working below and I get this error: 
"fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

I was following these instructions.

For more complex animations, run application from examples folder:
$ git clone git@github.com:shoutem/animation.git
$ cd animation/examples/ShoutemAnimation/
$ npm install
$ react-native run-ios

**Comment by SoHotSoup** [comment]
Hey @mgl97t!

Thank you for using our library.

There are two ways to achieve that effect. First, by using component `HeroHeader` it turns any RN component into `bounce-zoom-scroll-parallax` just take a look at this example to get how to recreate screen from that video: http://shoutem.github.io/docs/ui-toolkit/animation/combining-animations

There is event easiest way if you use `@shoutem/ui` components. Take a look at this code:
https://github.com/shoutem/ui/blob/develop/examples/RestaurantsApp/app/RestaurantDetails.js#L36

**Comment by SoHotSoup** [comment]
Regarding your cloning issue, I cannot reproduce it nor find out why you are not able to clone it. I am going check with some other account...

**Comment by mgl97t** [comment]
I opted for the @shoutem/ui way and it works great!

Thanks for all your help!

**Comment by SoHotSoup** [comment]
Thank you!
