### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by Gordyus** [shoutem/animation#12]
Hi,

On a fresh react native project, the command for install "npm install --save @shoutem/animation" give me the following error:

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "@shoutem/animation"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Invalid name: "@shoutem/animation"

Version react : 
react-native-cli: 2.0.1
react-native: 0.41.2

Version npm : 4.1.2

Thanks

**Comment by abarisic86** [comment]
This can be closed. It was issue with npm version and resolved. See here:
https://github.com/GeekyAnts/NativeBase/issues/578
