### ISSUE TITLE
Wrapping <Title> in <Parallax> causes React isMounted deprecation warning

### ISSUE THREAD

**Issue by joeferraro** [shoutem/animation#4]
"@shoutem/animation": "^0.8.7",
"@shoutem/ui": "^0.9.1",
"react-native": "^0.35.0"

I perused a bit and did not see any references to `isMounted`, but I confirmed this warning is only displaying when wrapping my `<Title/>` component in `<Parallax/>`. Any ideas?

Source code:

```
renderRow(category:any) {
    return (
      <TouchableOpacity onPress={() => Actions.Resource({id:'myresourceid'})}>
        <Image
        styleName="large-banner"
        source={category.image}>
          <Tile>
            <Parallax driver={this.driver} scrollSpeed={1.1}>
              <Title styleName="md-gutter-bottom">{category.body}</Title>
            </Parallax>
          </Tile>
        </Image>
      </TouchableOpacity>
    );
  }
```

![glass_and_iphone_6s_ _ios_10_0__14a345_](https://cloud.githubusercontent.com/assets/54157/20029895/5ca0280c-a32f-11e6-9779-0cb3c2917262.png)

**Comment by SoHotSoup** [comment]
Hey! Thank you for submitting this issue, I think this is because we use `NativeMethodsMixin.measure` inside of `Parallax` component. Maybe we will get rid of it in next release.

**Comment by tenodi** [comment]
`Parallax` component got updated in [v0.8.9]. Thanks for submitting this issue.

**Comment by joeferraro** [comment]
cheers, guys

**Comment by SoHotSoup** [comment]
actually use v0.8.10 :)
