### ISSUE TITLE
`useNativeDriver` possible?

### ISSUE THREAD

**Issue by adri** [shoutem/animation#6]
In React Native 0.38 native animation support was added on android. The `TouchableOpacity` and `TouchableBounce` were [updated already](https://github.com/facebook/react-native/commit/1bb323e256bb6ad7b9f757368e69cf682f71d7ac) to support this.

Would you be open to use this? Do you see anything speaking against using this for `FadeIn`/`FadeOut`?

**Comment by SoHotSoup** [comment]
Hey, I don't have anything against it. I was thinking about it and come across that native support should be part of the Drivers. Would you like to contribute with that?
